// data.js
// lista de todos os países do mundo com suas capitais, continente e uma curiosidade
// fonte: dados geograficos publicos (ONU / lista de paises soberanos reconhecidos)

const CAPITALS_DATA = [
  // ─── EUROPA ───────────────────────────────────────────────────────────────

  {
    country: "Alemanha",
    capital: "Berlim",
    continent: "Europe",
    fact: "Berlim tem mais pontes do que Veneza, mais de 1.700 no total.",
  },
  {
    country: "Andorra",
    capital: "Andorra la Vella",
    continent: "Europe",
    fact: "Andorra la Vella é a capital mais alta da Europa, a 1.023 metros de altitude.",
  },
  {
    country: "Áustria",
    capital: "Viena",
    continent: "Europe",
    fact: "Viena foi por muito tempo a capital do Sacro Império Romano-Germânico.",
  },
  {
    country: "Bélgica",
    capital: "Bruxelas",
    continent: "Europe",
    fact: "Bruxelas é sede da OTAN e de diversas instituições da União Europeia.",
  },
  {
    country: "Bielorrússia",
    capital: "Minsk",
    continent: "Europe",
    fact: "Minsk foi quase completamente destruída na Segunda Guerra Mundial e reconstruída do zero.",
  },
  {
    country: "Bósnia e Herzegovina",
    capital: "Sarajevo",
    continent: "Europe",
    fact: "Sarajevo foi a primeira cidade europeia a ter um bonde elétrico, em 1885.",
  },
  {
    country: "Bulgária",
    capital: "Sófia",
    continent: "Europe",
    fact: "Sófia é uma das cidades mais antigas da Europa, com mais de 7.000 anos de história.",
  },
  {
    country: "Croácia",
    capital: "Zagreb",
    continent: "Europe",
    fact: "Zagreb é lar do único museu das relações amorosas terminadas do mundo.",
  },
  {
    country: "Chipre",
    capital: "Nicósia",
    continent: "Europe",
    fact: "Nicósia é a última capital dividida do mundo, cortada ao meio desde 1974.",
  },
  {
    country: "Dinamarca",
    capital: "Copenhague",
    continent: "Europe",
    fact: "Copenhague é eleita consistentemente uma das cidades mais felizes e sustentáveis do mundo.",
  },
  {
    country: "Eslováquia",
    capital: "Bratislava",
    continent: "Europe",
    fact: "Bratislava é a única capital do mundo que faz fronteira com dois países diferentes.",
  },
  {
    country: "Eslovênia",
    capital: "Liubliana",
    continent: "Europe",
    fact: "Liubliana tem o centro histórico praticamente livre de carros, sendo uma cidade muito ciclável.",
  },
  {
    country: "Espanha",
    capital: "Madrid",
    continent: "Europe",
    fact: "Madrid é a capital europeia localizada na maior altitude, a 667 metros acima do mar.",
  },
  {
    country: "Estônia",
    capital: "Tallinn",
    continent: "Europe",
    fact: "Tallinn tem um dos centros históricos medievais mais bem preservados de toda a Europa.",
  },
  {
    country: "Finlândia",
    capital: "Helsinque",
    continent: "Europe",
    fact: "Helsinque tem o maior número de saunas por habitante do mundo.",
  },
  {
    country: "França",
    capital: "Paris",
    continent: "Europe",
    fact: "Paris é chamada de Cidade Luz por ter sido uma das primeiras a adotar iluminação pública.",
  },
  {
    country: "Grécia",
    capital: "Atenas",
    continent: "Europe",
    fact: "Atenas é considerada o berço da democracia ocidental, há mais de 2.500 anos.",
  },
  {
    country: "Hungria",
    capital: "Budapeste",
    continent: "Europe",
    fact: "Budapeste foi formada pela união de três cidades: Buda, Óbuda e Pest, em 1873.",
  },
  {
    country: "Irlanda",
    capital: "Dublin",
    continent: "Europe",
    fact: "Dublin é famosa por ter a maior densidade de pubs por habitante da Europa.",
  },
  {
    country: "Islândia",
    capital: "Reiquiavique",
    continent: "Europe",
    fact: "Reiquiavique é a capital mais ao norte do mundo e funciona 100% com energia renovável.",
  },
  {
    country: "Itália",
    capital: "Roma",
    continent: "Europe",
    fact: "Roma tem mais de 3.000 fontes públicas, entre as mais bonitas do mundo.",
  },
  {
    country: "Kosovo",
    capital: "Pristina",
    continent: "Europe",
    fact: "Pristina tem uma estátua de Bill Clinton em homenagem ao papel dos EUA na independência do Kosovo.",
  },
  {
    country: "Letônia",
    capital: "Riga",
    continent: "Europe",
    fact: "Riga tem a maior coleção de arquitetura Art Nouveau do mundo.",
  },
  {
    country: "Liechtenstein",
    capital: "Vaduz",
    continent: "Europe",
    fact: "Vaduz é uma das apenas duas capitais do mundo sem saída para o mar em país também sem saída para o mar.",
  },
  {
    country: "Lituânia",
    capital: "Vilnius",
    continent: "Europe",
    fact: "Vilnius tem o centro histórico barroco mais bem preservado da Europa do Norte.",
  },
  {
    country: "Luxemburgo",
    capital: "Luxemburgo",
    continent: "Europe",
    fact: "A cidade de Luxemburgo deu nome ao país e é sede do Tribunal de Justiça da UE.",
  },
  {
    country: "Malta",
    capital: "Valetta",
    continent: "Europe",
    fact: "Valetta é a menor capital da União Europeia, com menos de 1 km².",
  },
  {
    country: "Moldávia",
    capital: "Chisinau",
    continent: "Europe",
    fact: "Chisinau é conhecida pelas suas extensas áreas verdes, sendo chamada de cidade jardim.",
  },
  {
    country: "Mônaco",
    capital: "Mônaco",
    continent: "Europe",
    fact: "Mônaco é o segundo menor país do mundo e sua capital ocupa todo o território nacional.",
  },
  {
    country: "Montenegro",
    capital: "Podgorica",
    continent: "Europe",
    fact: "Podgorica foi chamada de Titograd durante a era comunista, em homenagem ao líder Josip Tito.",
  },
  {
    country: "Noruega",
    capital: "Oslo",
    continent: "Europe",
    fact: "Oslo foi renomeada de Christiania para seu nome atual apenas em 1925.",
  },
  {
    country: "Países Baixos",
    capital: "Amsterdã",
    continent: "Europe",
    fact: "Amsterdã tem mais bicicletas do que habitantes, cerca de 900 mil bikes.",
  },
  {
    country: "Polônia",
    capital: "Varsóvia",
    continent: "Europe",
    fact: "Varsóvia foi quase completamente destruída na Segunda Guerra Mundial e reconstruída tijolo a tijolo.",
  },
  {
    country: "Portugal",
    capital: "Lisboa",
    continent: "Europe",
    fact: "Lisboa é uma das cidades mais antigas da Europa, mais velha do que Roma.",
  },
  {
    country: "Reino Unido",
    capital: "Londres",
    continent: "Europe",
    fact: "Londres foi a primeira cidade do mundo a ter um sistema de metrô, inaugurado em 1863.",
  },
  {
    country: "República Tcheca",
    capital: "Praga",
    continent: "Europe",
    fact: "O Castelo de Praga é o maior castelo antigo do mundo, com 70.000 m².",
  },
  {
    country: "Romênia",
    capital: "Bucareste",
    continent: "Europe",
    fact: "O Palácio do Parlamento em Bucareste é o segundo maior edifício administrativo do mundo.",
  },
  {
    country: "Rússia",
    capital: "Moscou",
    continent: "Europe",
    fact: "Moscou abriga a Praça Vermelha e o Kremlin, um dos complexos históricos mais famosos do mundo.",
  },
  {
    country: "San Marino",
    capital: "San Marino",
    continent: "Europe",
    fact: "San Marino é o país mais antigo do mundo ainda existente, fundado em 301 d.C.",
  },
  {
    country: "Sérvia",
    capital: "Belgrado",
    continent: "Europe",
    fact: "Belgrado é uma das cidades habitadas mais antigas da Europa, com mais de 7.000 anos.",
  },
  {
    country: "Suécia",
    capital: "Estocolmo",
    continent: "Europe",
    fact: "Estocolmo é construída sobre 14 ilhas conectadas por 57 pontes.",
  },
  {
    country: "Suíça",
    capital: "Berna",
    continent: "Europe",
    fact: "Berna foi fundada em 1191 e seu centro histórico é Patrimônio Mundial da UNESCO.",
  },
  {
    country: "Ucrânia",
    capital: "Kiev",
    continent: "Europe",
    fact: "Kiev é uma das cidades mais antigas da Europa do Leste, fundada no século V.",
  },
  {
    country: "Vaticano",
    capital: "Cidade do Vaticano",
    continent: "Europe",
    fact: "A Cidade do Vaticano é o menor país do mundo, com apenas 0,44 km².",
  },

  // ─── ÁSIA ─────────────────────────────────────────────────────────────────

  {
    country: "Afeganistão",
    capital: "Cabul",
    continent: "Asia",
    fact: "Cabul fica a 1.800 metros de altitude e é uma das capitais mais altas do mundo.",
  },
  {
    country: "Arábia Saudita",
    capital: "Riade",
    continent: "Asia",
    fact: "Riade abriga o maior centro comercial do Oriente Médio e um dos maiores do mundo.",
  },
  {
    country: "Armênia",
    capital: "Yerevan",
    continent: "Asia",
    fact: "Yerevan é uma das cidades habitadas mais antigas do mundo, fundada em 782 a.C.",
  },
  {
    country: "Azerbaijão",
    capital: "Baku",
    continent: "Asia",
    fact: "Baku é a capital mais baixa do mundo, a 28 metros abaixo do nível do mar.",
  },
  {
    country: "Bahrein",
    capital: "Manama",
    continent: "Asia",
    fact: "Manama é um dos centros financeiros mais importantes do Oriente Médio.",
  },
  {
    country: "Bangladesh",
    capital: "Dhaka",
    continent: "Asia",
    fact: "Dhaka tem mais de 8 milhões de riquixás, o maior número de qualquer cidade do mundo.",
  },
  {
    country: "Brunei",
    capital: "Bandar Seri Begawan",
    continent: "Asia",
    fact: "Bandar Seri Begawan abriga a mesquita Omar Ali Saifuddien, uma das mais bonitas da Ásia.",
  },
  {
    country: "Butão",
    capital: "Timbu",
    continent: "Asia",
    fact: "Timbu é uma das poucas capitais do mundo sem semáforos, usando apenas guardas de trânsito.",
  },
  {
    country: "Camboja",
    capital: "Phnom Penh",
    continent: "Asia",
    fact: "Phnom Penh foi uma das cidades mais bonitas da Ásia durante o século XX.",
  },
  {
    country: "Cazaquistão",
    capital: "Astana",
    continent: "Asia",
    fact: "Astana foi construída no meio de uma estepe e é uma das cidades mais modernas da Ásia Central.",
  },
  {
    country: "China",
    capital: "Pequim",
    continent: "Asia",
    fact: "Pequim abriga a Cidade Proibida, o maior palácio imperial do mundo, com 9.999 quartos.",
  },
  {
    country: "Coreia do Norte",
    capital: "Pyongyang",
    continent: "Asia",
    fact: "Pyongyang tem poucas luzes à noite pois o país consome pouquíssima energia elétrica.",
  },
  {
    country: "Coreia do Sul",
    capital: "Seul",
    continent: "Asia",
    fact: "Seul tem uma das redes de internet mais rápidas do mundo e é um polo global de tecnologia.",
  },
  {
    country: "Emirados Árabes Unidos",
    capital: "Abu Dhabi",
    continent: "Asia",
    fact: "Abu Dhabi tem a maior mesquita do mundo fora da Arábia Saudita, a Grande Mesquita Sheikh Zayed.",
  },
  {
    country: "Filipinas",
    capital: "Manila",
    continent: "Asia",
    fact: "Manila é uma das cidades mais densamente populosas do mundo, com 70.000 hab/km².",
  },
  {
    country: "Geórgia",
    capital: "Tbilisi",
    continent: "Asia",
    fact: "Tbilisi tem um dos sistemas de escrita mais antigos do mundo, com mais de 1.500 anos.",
  },
  {
    country: "Índia",
    capital: "Nova Délhi",
    continent: "Asia",
    fact: "Nova Délhi é uma das regiões urbanas mais populosas do planeta, com mais de 32 milhões de hab.",
  },
  {
    country: "Indonésia",
    capital: "Jacarta",
    continent: "Asia",
    fact: "Jacarta está afundando cerca de 25 cm por ano, sendo a capital que mais afunda no mundo.",
  },
  {
    country: "Irã",
    capital: "Teerã",
    continent: "Asia",
    fact: "Teerã fica ao pé da Cordilheira de Alborz, onde está o monte Damavand, o mais alto do Irã.",
  },
  {
    country: "Iraque",
    capital: "Bagdá",
    continent: "Asia",
    fact: "Bagdá foi fundada em 762 d.C. como a Cidade Redonda, uma das primeiras cidades planejadas do mundo.",
  },
  {
    country: "Israel",
    capital: "Jerusalém",
    continent: "Asia",
    fact: "Jerusalém é cidade sagrada para três religiões: judaísmo, islamismo e cristianismo.",
  },
  {
    country: "Japão",
    capital: "Tóquio",
    continent: "Asia",
    fact: "Tóquio é a maior área metropolitana do mundo, com mais de 37 milhões de pessoas.",
  },
  {
    country: "Jordânia",
    capital: "Amã",
    continent: "Asia",
    fact: "Amã é construída sobre sete colinas e tem mais de 6.000 anos de história contínua.",
  },
  {
    country: "Kuwait",
    capital: "Cidade do Kuwait",
    continent: "Asia",
    fact: "A Cidade do Kuwait tem as Torres do Kuwait, símbolo arquitetônico do país desde 1979.",
  },
  {
    country: "Laos",
    capital: "Vienciana",
    continent: "Asia",
    fact: "Vienciana é a capital menos populosa do Sudeste Asiático, com ritmo de vida bem tranquilo.",
  },
  {
    country: "Líbano",
    capital: "Beirute",
    continent: "Asia",
    fact: "Beirute é chamada de Paris do Oriente Médio por sua vida cultural e noturna intensa.",
  },
  {
    country: "Malásia",
    capital: "Kuala Lumpur",
    continent: "Asia",
    fact: "As Torres Petronas em Kuala Lumpur foram as mais altas do mundo de 1998 a 2004.",
  },
  {
    country: "Maldivas",
    capital: "Malé",
    continent: "Asia",
    fact: "Malé é uma das cidades mais densas do mundo, com 65.000 pessoas em apenas 6 km².",
  },
  {
    country: "Mianmar",
    capital: "Naipidau",
    continent: "Asia",
    fact: "Naipidau foi construída do zero e inaugurada em 2006, substituindo Rangum como capital.",
  },
  {
    country: "Mongólia",
    capital: "Ulan Bator",
    continent: "Asia",
    fact: "Ulan Bator é a capital nacional mais fria do mundo, com temperatura média anual de -1,3°C.",
  },
  {
    country: "Nepal",
    capital: "Catmandu",
    continent: "Asia",
    fact: "Catmandu fica próxima ao Everest e é rodeada por sete Patrimônios Mundiais da UNESCO.",
  },
  {
    country: "Omã",
    capital: "Mascate",
    continent: "Asia",
    fact: "Mascate foi uma das cidades mais importantes do comércio marítimo do Oceano Índico por séculos.",
  },
  {
    country: "Paquistão",
    capital: "Islamabad",
    continent: "Asia",
    fact: "Islamabad foi construída do zero na década de 1960 para substituir Karachi como capital.",
  },
  {
    country: "Qatar",
    capital: "Doha",
    continent: "Asia",
    fact: "Doha sediou a Copa do Mundo FIFA de 2022, a primeira em um país árabe.",
  },
  {
    country: "Quirguistão",
    capital: "Bisqueque",
    continent: "Asia",
    fact: "Bisqueque fica em um vale rodeado pela majestosa Cordilheira Tian Shan.",
  },
  {
    country: "Síria",
    capital: "Damasco",
    continent: "Asia",
    fact: "Damasco é considerada uma das cidades continuamente habitadas mais antigas do mundo.",
  },
  {
    country: "Sri Lanka",
    capital: "Colombo",
    continent: "Asia",
    fact: "Colombo é o principal porto do sul da Ásia e um grande centro econômico regional.",
  },
  {
    country: "Tailândia",
    capital: "Bangkok",
    continent: "Asia",
    fact: "O nome oficial de Bangkok em tailandês tem 169 letras, o mais longo de uma capital no mundo.",
  },
  {
    country: "Tajiquistão",
    capital: "Duchambe",
    continent: "Asia",
    fact: "Duchambe significa segunda-feira em persa, pois cresceu a partir de um mercado semanal.",
  },
  {
    country: "Timor-Leste",
    capital: "Díli",
    continent: "Asia",
    fact: "Díli se tornou capital independente em 2002, quando Timor-Leste se tornou o país mais jovem do mundo.",
  },
  {
    country: "Turcomenistão",
    capital: "Asgabate",
    continent: "Asia",
    fact: "Asgabate tem o maior número de edifícios revestidos de mármore branco do mundo, segundo o Guinness.",
  },
  {
    country: "Turquia",
    capital: "Ancara",
    continent: "Asia",
    fact: "Ancara foi proclamada capital da Turquia em 1923 por Mustafa Kemal Atatürk.",
  },
  {
    country: "Uzbequistão",
    capital: "Tashkent",
    continent: "Asia",
    fact: "Tashkent é a maior cidade da Ásia Central, com mais de 2,5 milhões de habitantes.",
  },
  {
    country: "Vietnã",
    capital: "Hanói",
    continent: "Asia",
    fact: "Hanói é uma das cidades mais antigas da Ásia, com mais de 1.000 anos de história.",
  },
  {
    country: "Iêmen",
    capital: "Sanaa",
    continent: "Asia",
    fact: "Sanaa é uma das cidades mais antigas do mundo, com construções de mais de 2.500 anos.",
  },

  // ─── ÁFRICA ───────────────────────────────────────────────────────────────

  {
    country: "África do Sul",
    capital: "Pretória",
    continent: "Africa",
    fact: "A África do Sul é o único país do mundo com três capitais: Pretória, Cidade do Cabo e Bloemfontein.",
  },
  {
    country: "Argélia",
    capital: "Argel",
    continent: "Africa",
    fact: "Argel é chamada de Argel a Branca por seus edifícios caiados nas colinas que dão para o mar.",
  },
  {
    country: "Angola",
    capital: "Luanda",
    continent: "Africa",
    fact: "Luanda foi uma das cidades mais caras do mundo para expatriados durante os anos 2010.",
  },
  {
    country: "Benin",
    capital: "Porto Novo",
    continent: "Africa",
    fact: "Porto-Novo é a capital oficial, mas Cotonou é a maior cidade e sede do governo na prática.",
  },
  {
    country: "Botswana",
    capital: "Gaborone",
    continent: "Africa",
    fact: "Gaborone é uma das cidades que mais cresceu no mundo nas últimas décadas, impulsionada pelos diamantes.",
  },
  {
    country: "Burkina Faso",
    capital: "Uagadugu",
    continent: "Africa",
    fact: "Uagadugu significa honra à pátria em língua mossi, o idioma local mais falado.",
  },
  {
    country: "Burundi",
    capital: "Gitega",
    continent: "Africa",
    fact: "Gitega substituiu Bujumbura como capital oficial do Burundi em 2019.",
  },
  {
    country: "Cabo Verde",
    capital: "Praia",
    continent: "Africa",
    fact: "Praia fica na ilha de Santiago e é a maior cidade do arquipélago de Cabo Verde.",
  },
  {
    country: "Camarões",
    capital: "Iaundê",
    continent: "Africa",
    fact: "Iaundê fica no planalto central e tem um clima bem mais ameno que a cidade costeira de Douala.",
  },
  {
    country: "Chade",
    capital: "Djamena",
    continent: "Africa",
    fact: "Jamena fica na confluência dos rios Chari e Logona, perto do Lago Chade.",
  },
  {
    country: "Comores",
    capital: "Moroni",
    continent: "Africa",
    fact: "Moroni fica na base do vulcão Kartala, um dos maiores vulcões ativos do mundo.",
  },
  {
    country: "Congo",
    capital: "Brazzaville",
    continent: "Africa",
    fact: "Brazzaville e Kinshasa são as duas capitais mais próximas do mundo, separadas apenas pelo Rio Congo.",
  },
  {
    country: "Costa do Marfim",
    capital: "Yamussucro",
    continent: "Africa",
    fact: "Yamussucro tem a maior basílica cristã do mundo, a Nossa Senhora da Paz.",
  },
  {
    country: "Djibuti",
    capital: "Djibuti",
    continent: "Africa",
    fact: "A cidade de Djibuti é um dos portos estratégicos mais importantes do Corno da África.",
  },
  {
    country: "Egito",
    capital: "Cairo",
    continent: "Africa",
    fact: "O Cairo é a maior cidade da África e fica próxima às famosas Pirâmides de Gizé.",
  },
  {
    country: "Eritreia",
    capital: "Asmara",
    continent: "Africa",
    fact: "Asmara tem uma das maiores coleções de arquitetura Art Déco do mundo, herança italiana.",
  },
  {
    country: "Eswatini",
    capital: "Mbabane",
    continent: "Africa",
    fact: "Mbabane é a capital administrativa, mas Lobamba é a capital real e legislativa do país.",
  },
  {
    country: "Etiópia",
    capital: "Adis Abeba",
    continent: "Africa",
    fact: "Adis Abeba significa Nova Flor em amárico e é sede da União Africana.",
  },
  {
    country: "Gabão",
    capital: "Libreville",
    continent: "Africa",
    fact: "Libreville significa cidade livre e foi fundada por escravos libertados em 1849.",
  },
  {
    country: "Gâmbia",
    capital: "Banjul",
    continent: "Africa",
    fact: "Banjul fica em uma ilha rodeada pelo Rio Gâmbia e pelo Oceano Atlântico.",
  },
  {
    country: "Gana",
    capital: "Acra",
    continent: "Africa",
    fact: "Acra é uma das cidades mais cosmopolitas da África Ocidental e hub econômico da região.",
  },
  {
    country: "Guiné",
    capital: "Conacri",
    continent: "Africa",
    fact: "Conacri fica em uma península e é cercada pelo Oceano Atlântico em três lados.",
  },
  {
    country: "Guiné-Bissau",
    capital: "Bissau",
    continent: "Africa",
    fact: "Bissau fica às margens do Rio Geba e tem arquitetura colonial portuguesa bem preservada.",
  },
  {
    country: "Guiné Equatorial",
    capital: "Ciudad de la Paz",
    continent: "Africa",
    fact: "Ciudad de la Paz foi oficializada como nova capital em 2 de janeiro de 2026, substituindo Malabo.",
  },
  {
    country: "Lesoto",
    capital: "Maseru",
    continent: "Africa",
    fact: "Maseru é cercada completamente pela África do Sul, pois o Lesoto é um enclave.",
  },
  {
    country: "Libéria",
    capital: "Monróvia",
    continent: "Africa",
    fact: "Monróvia foi nomeada em homenagem ao presidente americano James Monroe, fundador da cidade.",
  },
  {
    country: "Líbia",
    capital: "Trípoli",
    continent: "Africa",
    fact: "Trípoli tem uma medina muito bem preservada que é Patrimônio Mundial da UNESCO.",
  },
  {
    country: "Madagáscar",
    capital: "Antananarivo",
    continent: "Africa",
    fact: "Antananarivo fica num planalto a 1.275 metros e é chamada de Cidade das Mil Aldeias.",
  },
  {
    country: "Malauí",
    capital: "Lilongwe",
    continent: "Africa",
    fact: "Lilongwe substituiu Zomba como capital do Malauí em 1975 por estar mais centralizada.",
  },
  {
    country: "Mali",
    capital: "Bamako",
    continent: "Africa",
    fact: "Bamako é uma das cidades que mais cresce no mundo, dobrando de tamanho a cada dez anos.",
  },
  {
    country: "Marrocos",
    capital: "Rabat",
    continent: "Africa",
    fact: "Rabat fica às margens do rio Bou Regreg e seu centro histórico é Patrimônio Mundial da UNESCO.",
  },
  {
    country: "Mauritânia",
    capital: "Nouakchott",
    continent: "Africa",
    fact: "Nuakchott foi construída no deserto e cresceu de uma aldeia de 600 pessoas para uma metrópole.",
  },
  {
    country: "Maurício",
    capital: "Porto Luís",
    continent: "Africa",
    fact: "Porto Luís é um dos centros financeiros mais competitivos da África.",
  },
  {
    country: "Moçambique",
    capital: "Maputo",
    continent: "Africa",
    fact: "Maputo, antes chamada Lourenço Marques, tem uma arquitetura colonial portuguesa única na África.",
  },
  {
    country: "Namíbia",
    capital: "Windhoek",
    continent: "Africa",
    fact: "Windhoek é uma das capitais mais limpas e organizadas de toda a África.",
  },
  {
    country: "Níger",
    capital: "Niamei",
    continent: "Africa",
    fact: "Niamei fica às margens do Rio Níger e é um dos principais centros do Sahel.",
  },
  {
    country: "Nigéria",
    capital: "Abuja",
    continent: "Africa",
    fact: "Abuja foi construída para substituir Lagos como capital em 1991 por estar no centro do país.",
  },
  {
    country: "Quênia",
    capital: "Nairóbi",
    continent: "Africa",
    fact: "Nairóbi é a única capital do mundo com um parque nacional dentro da área urbana.",
  },
  {
    country: "República Centro-Africana",
    capital: "Bangui",
    continent: "Africa",
    fact: "Bangui fica às margens do Rio Ubangui, na fronteira com a República Democrática do Congo.",
  },
  {
    country: "República Democrática do Congo",
    capital: "Kinshasa",
    continent: "Africa",
    fact: "Kinshasa é a maior cidade francófona do mundo, maior até do que Paris.",
  },
  {
    country: "Ruanda",
    capital: "Kigali",
    continent: "Africa",
    fact: "Kigali é considerada uma das cidades mais limpas e seguras da África.",
  },
  {
    country: "São Tomé e Príncipe",
    capital: "São Tomé",
    continent: "Africa",
    fact: "São Tomé fica quase exatamente no ponto zero do globo, cruzamento do equador com o meridiano.",
  },
  {
    country: "Senegal",
    capital: "Dacar",
    continent: "Africa",
    fact: "Dacar é o ponto mais ocidental do continente africano.",
  },
  {
    country: "Serra Leoa",
    capital: "Freetown",
    continent: "Africa",
    fact: "Freetown foi fundada por escravos libertos em 1792, daí o nome Cidade Livre.",
  },
  {
    country: "Seychelles",
    capital: "Victoria",
    continent: "Africa",
    fact: "Victoria é a menor capital de um país soberano em território africano.",
  },
  {
    country: "Somália",
    capital: "Mogadíscio",
    continent: "Africa",
    fact: "Mogadíscio é uma das cidades mais antigas da África Oriental, com mais de 1.000 anos.",
  },
  {
    country: "Sudão",
    capital: "Cartum",
    continent: "Africa",
    fact: "Cartum fica na confluência dos rios Nilo Azul e Nilo Branco, formando o grande Rio Nilo.",
  },
  {
    country: "Sudão do Sul",
    capital: "Juba",
    continent: "Africa",
    fact: "Juba é a capital do país mais jovem do mundo, independente desde 2011.",
  },
  {
    country: "Tanzânia",
    capital: "Dodoma",
    continent: "Africa",
    fact: "Dodoma substituiu Dar es Salaam como capital oficial da Tanzânia em 1996.",
  },
  {
    country: "Togo",
    capital: "Lomé",
    continent: "Africa",
    fact: "Lomé é uma das poucas capitais africanas que faz fronteira direta com outro país.",
  },
  {
    country: "Tunísia",
    capital: "Túnis",
    continent: "Africa",
    fact: "A antiga Cartago, hoje parte da área metropolitana de Túnis, foi fundada em 814 a.C.",
  },
  {
    country: "Uganda",
    capital: "Kampala",
    continent: "Africa",
    fact: "Kampala é construída sobre sete colinas, assim como Roma e Lisboa.",
  },
  {
    country: "Zâmbia",
    capital: "Lusaka",
    continent: "Africa",
    fact: "Lusaka foi projetada pelos britânicos no período colonial e tem um traçado urbano bem planejado.",
  },
  {
    country: "Zimbábue",
    capital: "Harare",
    continent: "Africa",
    fact: "Harare significa lugar que não dorme na língua Shona dos povos locais.",
  },

  // ─── AMÉRICAS DO NORTE E CENTRAL ──────────────────────────────────────────

  {
    country: "Antígua e Barbuda",
    capital: "Saint John's",
    continent: "North America",
    fact: "Saint John's é um dos portos naturais mais bonitos do Caribe.",
  },
  {
    country: "Bahamas",
    capital: "Nassau",
    continent: "North America",
    fact: "Nassau é o principal destino turístico do Caribe, famosa pelas praias de areia branca.",
  },
  {
    country: "Barbados",
    capital: "Bridgetown",
    continent: "North America",
    fact: "Bridgetown tem o centro histórico tombado como Patrimônio Mundial da UNESCO.",
  },
  {
    country: "Belize",
    capital: "Belmopan",
    continent: "North America",
    fact: "Belmopan foi construída do zero nos anos 1970 para substituir a capital Belize City.",
  },
  {
    country: "Canadá",
    capital: "Ottawa",
    continent: "North America",
    fact: "Ottawa abriga o canal Rideau, o maior rinque de patinação ao ar livre do mundo.",
  },
  {
    country: "Costa Rica",
    capital: "San José",
    continent: "North America",
    fact: "San José é cercada por vulcões ativos e fica num vale a 1.170 metros de altitude.",
  },
  {
    country: "Cuba",
    capital: "Havana",
    continent: "North America",
    fact: "Havana é famosa pelos carros clássicos americanos dos anos 1950 que ainda circulam pelas ruas.",
  },
  {
    country: "Dominica",
    capital: "Roseau",
    continent: "North America",
    fact: "Roseau é a capital de uma ilha chamada de Ilha da Natureza pelo seu ambiente praticamente intocado.",
  },
  {
    country: "El Salvador",
    capital: "San Salvador",
    continent: "North America",
    fact: "San Salvador foi destruída por terremotos várias vezes e reconstruída em diferentes locais.",
  },
  {
    country: "Estados Unidos",
    capital: "Washington D.C.",
    continent: "North America",
    fact: "Washington D.C. foi especialmente projetada como capital e não pertence a nenhum estado.",
  },
  {
    country: "Granada",
    capital: "Saint George's",
    continent: "North America",
    fact: "Saint George's é considerada uma das cidades mais bonitas do Caribe, com porto natural em ferradura.",
  },
  {
    country: "Guatemala",
    capital: "Cidade da Guatemala",
    continent: "North America",
    fact: "A Cidade da Guatemala foi fundada em 1776 após um terremoto destruir a antiga capital.",
  },
  {
    country: "Haiti",
    capital: "Porto Príncipe",
    continent: "North America",
    fact: "Porto Príncipe foi fundada pelos franceses em 1749 e foi um dos centros da Revolução Haitiana.",
  },
  {
    country: "Honduras",
    capital: "Tegucigalpa",
    continent: "North America",
    fact: "Tegucigalpa é uma das poucas capitais do mundo sem acesso ferroviário.",
  },
  {
    country: "Jamaica",
    capital: "Kingston",
    continent: "North America",
    fact: "Kingston abriga o maior estúdio de música do Caribe, berço do reggae e do dancehall.",
  },
  {
    country: "México",
    capital: "Cidade do México",
    continent: "North America",
    fact: "A Cidade do México foi construída sobre o lago Texcoco, sítio da antiga civilização asteca.",
  },
  {
    country: "Nicarágua",
    capital: "Manágua",
    continent: "North America",
    fact: "Manágua fica às margens do Lago Manágua e sobreviveu a um terremoto devastador em 1972.",
  },
  {
    country: "Panamá",
    capital: "Cidade do Panamá",
    continent: "North America",
    fact: "A Cidade do Panamá é a única capital do mundo com uma floresta tropical dentro da área urbana.",
  },
  {
    country: "República Dominicana",
    capital: "Santo Domingo",
    continent: "North America",
    fact: "Santo Domingo foi a primeira cidade europeia permanente das Américas, fundada em 1498.",
  },
  {
    country: "São Cristóvão e Nevis",
    capital: "Basseterre",
    continent: "North America",
    fact: "Basseterre é uma das menores capitais das Américas, com apenas 15.000 habitantes.",
  },
  {
    country: "Santa Lúcia",
    capital: "Castries",
    continent: "North America",
    fact: "Castries tem um dos melhores portos naturais do Caribe.",
  },
  {
    country: "São Vicente e Granadinas",
    capital: "Kingstown",
    continent: "North America",
    fact: "Kingstown é famosa pelos seus jardins botânicos, fundados em 1765, os mais antigos do hemisfério ocidental.",
  },
  {
    country: "Trinidad e Tobago",
    capital: "Porto da Espanha",
    continent: "North America",
    fact: "Porto da Espanha é conhecida pelo Carnaval, um dos mais vibrantes do mundo depois do Rio.",
  },

  // ─── AMÉRICAS DO SUL ──────────────────────────────────────────────────────

  {
    country: "Argentina",
    capital: "Buenos Aires",
    continent: "South America",
    fact: "Buenos Aires é chamada de Paris da América do Sul por sua arquitetura europeia.",
  },
  {
    country: "Bolívia",
    capital: "Sucre",
    continent: "South America",
    fact: "Sucre é a capital constitucional da Bolívia, mas La Paz é a sede do governo e parlamento.",
  },
  {
    country: "Brasil",
    capital: "Brasília",
    continent: "South America",
    fact: "Brasília foi construída em apenas 41 meses e inaugurada em 1960. É Patrimônio Mundial da UNESCO.",
  },
  {
    country: "Chile",
    capital: "Santiago",
    continent: "South America",
    fact: "Santiago fica no vale central do Chile, com a Cordilheira dos Andes visível da cidade.",
  },
  {
    country: "Colômbia",
    capital: "Bogotá",
    continent: "South America",
    fact: "Bogotá fica a 2.600 metros de altitude e é uma das capitais mais altas do mundo.",
  },
  {
    country: "Equador",
    capital: "Quito",
    continent: "South America",
    fact: "Quito foi a primeira cidade declarada Patrimônio Cultural da Humanidade pela UNESCO em 1978.",
  },
  {
    country: "Guiana",
    capital: "Georgetown",
    continent: "South America",
    fact: "Georgetown é a única capital de língua inglesa da América do Sul.",
  },
  {
    country: "Guiana Francesa",
    capital: "Caiena",
    continent: "South America",
    fact: "Caiena é um território ultramarino da França e abriga a Base de Lançamento de Kourou da ESA.",
  },
  {
    country: "Paraguai",
    capital: "Assunção",
    continent: "South America",
    fact: "Assunção é uma das cidades mais antigas da América do Sul, fundada em 1537.",
  },
  {
    country: "Peru",
    capital: "Lima",
    continent: "South America",
    fact: "Lima está localizada no deserto costeiro do Peru e raramente recebe chuvas.",
  },
  {
    country: "Suriname",
    capital: "Paramaribo",
    continent: "South America",
    fact: "Paramaribo tem o centro histórico mais bem preservado da América do Sul, de estilo holandês.",
  },
  {
    country: "Uruguai",
    capital: "Montevidéu",
    continent: "South America",
    fact: "Montevidéu é constantemente eleita a melhor cidade da América Latina para se viver.",
  },
  {
    country: "Venezuela",
    capital: "Caracas",
    continent: "South America",
    fact: "Caracas está rodeada por montanhas e tem um dos climas mais agradáveis da América do Sul.",
  },

  // ─── OCEANIA ──────────────────────────────────────────────────────────────

  {
    country: "Austrália",
    capital: "Camberra",
    continent: "Oceania",
    fact: "Camberra foi construída para resolver a rivalidade entre Sydney e Melbourne pela capital.",
  },
  {
    country: "Fiji",
    capital: "Suva",
    continent: "Oceania",
    fact: "Suva fica na Ilha de Viti Levu e é o centro econômico e político do Pacífico Sul.",
  },
  {
    country: "Ilhas Marshall",
    capital: "Majuro",
    continent: "Oceania",
    fact: "Majuro é um atol de baixíssima altitude e está entre os territórios mais ameaçados pela elevação do mar.",
  },
  {
    country: "Ilhas Salomão",
    capital: "Honiara",
    continent: "Oceania",
    fact: "Honiara fica na ilha de Guadalcanal, palco de batalhas decisivas da Segunda Guerra Mundial.",
  },
  {
    country: "Kiribati",
    capital: "Tarawa do Sul",
    continent: "Oceania",
    fact: "Tarawa do Sul é um dos lugares mais densamente populosos do mundo para uma ilha tão pequena.",
  },
  {
    country: "Micronésia",
    capital: "Palikir",
    continent: "Oceania",
    fact: "Palikir é uma das menores capitais do mundo, localizada na ilha de Pohnpei.",
  },
  {
    country: "Nauru",
    capital: "Yaren",
    continent: "Oceania",
    fact: "Yaren não é capital oficial, mas é o maior distrito e sede do governo de Nauru.",
  },
  {
    country: "Nova Zelândia",
    capital: "Wellington",
    continent: "Oceania",
    fact: "Wellington é a capital mais ao sul do mundo e apelidada de Windy Wellington pelos ventos fortes.",
  },
  {
    country: "Palau",
    capital: "Ngerulmud",
    continent: "Oceania",
    fact: "Ngerulmud é a capital menos populosa do mundo, com apenas algumas centenas de habitantes.",
  },
  {
    country: "Papua Nova Guiné",
    capital: "Port Moresby",
    continent: "Oceania",
    fact: "Papua Nova Guiné tem mais de 800 línguas nativas, mais do que qualquer outro país no mundo.",
  },
  {
    country: "Samoa",
    capital: "Apia",
    continent: "Oceania",
    fact: "Apia foi o lar do escritor escocês Robert Louis Stevenson nos seus últimos anos de vida.",
  },
  {
    country: "Tonga",
    capital: "Nukualofa",
    continent: "Oceania",
    fact: "Nukualofa é a capital de um dos últimos reinos monarquistas do Pacífico.",
  },
  {
    country: "Tuvalu",
    capital: "Funafuti",
    continent: "Oceania",
    fact: "Funafuti pode ser a primeira capital a desaparecer completamente pelo aumento do nível do mar.",
  },
  {
    country: "Vanuatu",
    capital: "Port Vila",
    continent: "Oceania",
    fact: "Port Vila foi eleita uma das cidades mais felizes do planeta em pesquisas de bem-estar global.",
  },
];
